# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(251, 264)
        Dialog.setMinimumSize(QtCore.QSize(251, 264))
        Dialog.setMaximumSize(QtCore.QSize(251, 264))
        Dialog.setAccessibleName("")
        Dialog.setStyleSheet("background-color: rgb(65, 65, 65);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(100, 70, 58, 18))
        self.label.setStyleSheet("color: rgb(255, 255, 255);font-size:16px;")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(100, 140, 58, 18))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);font-size:16px;")
        self.label_2.setObjectName("label_2")
        self.login_authorization = QtWidgets.QLineEdit(Dialog)
        self.login_authorization.setGeometry(QtCore.QRect(20, 100, 211, 32))
        self.login_authorization.setStyleSheet("color: rgb(245, 245, 245);")
        self.login_authorization.setAlignment(QtCore.Qt.AlignCenter)
        self.login_authorization.setObjectName("login_authorization")
        self.password_authorization = QtWidgets.QLineEdit(Dialog)
        self.password_authorization.setGeometry(QtCore.QRect(20, 160, 211, 32))
        self.password_authorization.setAutoFillBackground(False)
        self.password_authorization.setStyleSheet("color: rgb(245, 245, 245);")
        self.password_authorization.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_authorization.setAlignment(QtCore.Qt.AlignCenter)
        self.password_authorization.setObjectName("password_authorization")
        self.button_authorization = QtWidgets.QPushButton(Dialog)
        self.button_authorization.setGeometry(QtCore.QRect(20, 210, 211, 34))
        self.button_authorization.setStyleSheet("color: rgb(255, 255, 255);")
        self.button_authorization.setObjectName("button_authorization")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 20, 221, 41))
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);font-size:16px;")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Авторизация"))
        self.label.setText(_translate("Dialog", "Логин"))
        self.label_2.setText(_translate("Dialog", "Пароль"))
        self.login_authorization.setText(_translate("Dialog", "user"))
        self.password_authorization.setText(_translate("Dialog", "User123456"))
        self.button_authorization.setText(_translate("Dialog", "Авторизация"))
        self.label_3.setText(_translate("Dialog", "Введите учетную запись  компьютера (root)"))
