# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'other.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(307, 90)
        Dialog.setMinimumSize(QtCore.QSize(307, 90))
        Dialog.setMaximumSize(QtCore.QSize(307, 90))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 91, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.button_script_1 = QtWidgets.QPushButton(Dialog)
        self.button_script_1.setGeometry(QtCore.QRect(110, 30, 88, 34))
        self.button_script_1.setObjectName("button_script_1")
        self.button_inventory = QtWidgets.QPushButton(Dialog)
        self.button_inventory.setGeometry(QtCore.QRect(10, 30, 88, 34))
        self.button_inventory.setObjectName("button_inventory")
        self.button_script_2 = QtWidgets.QPushButton(Dialog)
        self.button_script_2.setGeometry(QtCore.QRect(210, 30, 88, 34))
        self.button_script_2.setObjectName("button_script_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 10, 91, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Разное"))
        self.label.setText(_translate("Dialog", "Инвенториз."))
        self.label_2.setText(_translate("Dialog", "Скрипт №1"))
        self.button_script_1.setText(_translate("Dialog", "Установить"))
        self.button_inventory.setText(_translate("Dialog", "Установить"))
        self.button_script_2.setText(_translate("Dialog", "Установить"))
        self.label_3.setText(_translate("Dialog", "Скрипт №2"))
