# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'proxy.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(304, 81)
        Dialog.setMinimumSize(QtCore.QSize(304, 81))
        Dialog.setMaximumSize(QtCore.QSize(304, 81))
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(110, 10, 91, 20))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(10, 10, 91, 20))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.button_proxy_fap = QtWidgets.QPushButton(Dialog)
        self.button_proxy_fap.setGeometry(QtCore.QRect(210, 30, 88, 34))
        self.button_proxy_fap.setObjectName("button_proxy_fap")
        self.button_proxy_all = QtWidgets.QPushButton(Dialog)
        self.button_proxy_all.setGeometry(QtCore.QRect(10, 30, 88, 34))
        self.button_proxy_all.setObjectName("button_proxy_all")
        self.button_proxy_no = QtWidgets.QPushButton(Dialog)
        self.button_proxy_no.setGeometry(QtCore.QRect(110, 30, 88, 34))
        self.button_proxy_no.setObjectName("button_proxy_no")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(210, 10, 91, 20))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", "Без прокси"))
        self.label.setText(_translate("Dialog", "Для всех"))
        self.button_proxy_fap.setText(_translate("Dialog", "Установить"))
        self.button_proxy_all.setText(_translate("Dialog", "Установить"))
        self.button_proxy_no.setText(_translate("Dialog", "Установить"))
        self.label_3.setText(_translate("Dialog", "Для ФАП"))
